/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/r/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity */
        get: operations["identity_r_identity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/r/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_r_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/r/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Requests
         * @description Stored requests, web and agent, newest first. Polls the owner for open ones and verifies on arrival.
         */
        get: operations["requests_r_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/r/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Storage */
        get: operations["storage_r_storage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RAskIn */
        RAskIn: {
            /** Question */
            question: string;
        };
        /** RAskOut */
        RAskOut: {
            /** Local Id */
            local_id: string;
            /** Request Id */
            request_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending_pairing" | "pending" | "done";
        };
        /** RIdentity */
        RIdentity: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Fingerprint */
            fingerprint: string;
            /** Owner Url */
            owner_url: string;
            /**
             * Owner Reachable
             * @default false
             */
            owner_reachable: boolean;
        };
        /** RRequest */
        RRequest: {
            /** Local Id */
            local_id: string;
            /** Request Id */
            request_id: string;
            /** Question */
            question: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending_pairing" | "pending" | "done";
            /**
             * Via
             * @enum {string}
             */
            via: "web" | "agent";
            result?: components["schemas"]["VerifierOutput"] | null;
        };
        /** RStorage */
        RStorage: {
            /** Files */
            files: components["schemas"]["RStorageFile"][];
        };
        /** RStorageFile */
        RStorageFile: {
            /** Name */
            name: string;
            /** Size */
            size: number;
            /** Preview Json */
            preview_json: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifierCheck */
        VerifierCheck: {
            /** Name */
            name: string;
            /** Ok */
            ok: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /**
         * VerifierOutput
         * @description `claim` is the disclosed issuer claim name, or the attested claim rendered as text (§6.4).
         */
        VerifierOutput: {
            /**
             * Answer Type
             * @enum {string}
             */
            answer_type: "ISSUER_PROOF" | "OWNER_ATTESTED" | "DECLINED" | "CANNOT_CONFIRM" | "REFUSED";
            /** Claim */
            claim: string;
            /** Result */
            result?: boolean | string | null;
            /** Checks */
            checks: components["schemas"]["VerifierCheck"][];
            /** All Ok */
            all_ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    identity_r_identity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RIdentity"];
                };
            };
        };
    };
    ask_r_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RAskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RAskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requests_r_requests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RRequest"][];
                };
            };
        };
    };
    storage_r_storage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RStorage"];
                };
            };
        };
    };
}
