/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Upload
         * @description Copies into vault/<subdir>/ for the watcher. Never overwrites: same bytes -> 200, different -> 409.
         */
        post: operations["ingest_upload_api_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Sync */
        post: operations["ingest_sync_api_ingest_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ingest Events */
        get: operations["ingest_events_api_ingest_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Documents */
        get: operations["documents_api_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity Anchor */
        get: operations["identity_anchor_api_identity_get"];
        put?: never;
        post?: never;
        /**
         * Identity Remove
         * @description CONTRACT §6.6: retire the owner's Aadhaar anchor; 409 when the anchor comes from a document.
         */
        delete: operations["identity_remove_api_identity_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/aadhaar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Identity Aadhaar
         * @description CONTRACT §6.6: the owner's UIDAI offline e-KYC ZIP + share code. Read in memory; never written or echoed.
         */
        post: operations["identity_aadhaar_api_identity_aadhaar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entities */
        get: operations["entities_api_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facts */
        get: operations["facts_api_facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Graph */
        get: operations["graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chunk */
        get: operations["chunk_api_chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Sync */
        post: operations["chat_sync_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Teach */
        post: operations["teach_api_memory_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/candidates/{candidate_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Candidate Decision */
        post: operations["candidate_decision_api_memory_candidates__candidate_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Memory Timeline */
        get: operations["memory_timeline_api_memory_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tasks */
        get: operations["tasks_api_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Task Decision */
        post: operations["task_decision_api_tasks__task_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue
         * @description All requesters (pending first-contact and paired), undecided requests and planned tasks.
         */
        get: operations["queue_api_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requesters/{fp}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requester Decision */
        post: operations["requester_decision_api_requesters__fp__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Decision */
        post: operations["request_decision_api_requests__request_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wallet Status */
        get: operations["wallet_status_api_wallet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Log */
        get: operations["audit_log_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Outbox */
        get: operations["outbox_api_outbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ask/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ask Result */
        get: operations["ask_result_api_ask__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Claims */
        get: operations["claims_api_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskAck */
        AskAck: {
            /** Request Id */
            request_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending_pairing" | "pending" | "done";
        };
        /**
         * AskIn
         * @description POST /api/ask. `sig` covers canonical JSON of all other fields. `ts` is Unix seconds (int), within 120 s.
         */
        AskIn: {
            /** Requester Pubkey */
            requester_pubkey: string;
            /** Requester Name */
            requester_name: string;
            /** Requester Type */
            requester_type: string;
            /** Question */
            question: string;
            /** Nonce */
            nonce: string;
            /** Ts */
            ts: number;
            /** Sig */
            sig: string;
        };
        /**
         * AskResult
         * @description GET /api/ask/{id}. `payload` is a Presentation or Attestation dict, or null.
         */
        AskResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending_pairing" | "pending" | "done";
            /** Answer Type */
            answer_type?: ("ISSUER_PROOF" | "OWNER_ATTESTED" | "DECLINED" | "CANNOT_CONFIRM" | "REFUSED") | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
            /** Owner Pairwise Pubkey */
            owner_pairwise_pubkey?: string | null;
        };
        /** Attachment */
        Attachment: {
            /**
             * Type
             * @default presentation
             * @constant
             */
            type: "presentation";
            /** Request Id */
            request_id: string;
        };
        /** AuditEntry */
        AuditEntry: {
            /** Seq */
            seq: number;
            /** Ts */
            ts: string;
            /**
             * Event
             * @enum {string}
             */
            event: "ingested" | "document_signature_failed" | "document_removed" | "requester_pending" | "requester_paired" | "requester_blocked" | "request_received" | "request_auto_refused" | "request_cannot_confirm" | "request_refused_ledger" | "disclosure_answered" | "disclosure_declined" | "disclosure_denied" | "memory_taught" | "memory_candidate_accepted" | "task_planned" | "task_approved" | "task_rejected" | "task_executed" | "task_failed" | "wallet_low" | "request_rejected" | "identity_verified" | "identity_verify_failed" | "identity_removed";
            /** Ref Id */
            ref_id?: string | null;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Prev Hash */
            prev_hash: string;
            /** Entry Hash */
            entry_hash: string;
        };
        /** AuditOut */
        AuditOut: {
            /** Entries */
            entries: components["schemas"]["AuditEntry"][];
            /** Chain Intact */
            chain_intact: boolean;
            /** Broken At */
            broken_at?: number | null;
        };
        /** Body_identity_aadhaar_api_identity_aadhaar_post */
        Body_identity_aadhaar_api_identity_aadhaar_post: {
            /** File */
            file: string;
            /** Share Code */
            share_code: string;
        };
        /** Body_ingest_upload_api_ingest_post */
        Body_ingest_upload_api_ingest_post: {
            /** File */
            file: string;
        };
        /** CandidateDecisionIn */
        CandidateDecisionIn: {
            /** Remember */
            remember: boolean;
        };
        /** CandidateDecisionOut */
        CandidateDecisionOut: {
            /** Stored */
            stored: components["schemas"]["Fact"] | components["schemas"]["Entity"] | null;
        };
        /** ChatDoneData */
        ChatDoneData: {
            /** Latency Ms */
            latency_ms: number;
            /** First Token Ms */
            first_token_ms: number;
            /** Prompt Tokens */
            prompt_tokens?: number | null;
        };
        /** ChatDoneEvent */
        ChatDoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "done";
            data: components["schemas"]["ChatDoneData"];
        };
        /** ChatErrorData */
        ChatErrorData: {
            /** Message */
            message: string;
        };
        /** ChatErrorEvent */
        ChatErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "error";
            data: components["schemas"]["ChatErrorData"];
        };
        /**
         * ChatFinal
         * @description Data of the §10 `final` event.
         */
        ChatFinal: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Citation Ok */
            citation_ok: boolean;
            /** Flags */
            flags?: string[];
            /** Memory Candidates */
            memory_candidates?: components["schemas"]["MemoryCandidate"][];
            /** Excluded Docs */
            excluded_docs?: string[];
        };
        /** ChatFinalEvent */
        ChatFinalEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "final";
            data: components["schemas"]["ChatFinal"];
        };
        /** ChatIn */
        ChatIn: {
            /** Question */
            question: string;
            /** History */
            history?: components["schemas"]["ChatTurn"][];
        };
        /** ChatMetaData */
        ChatMetaData: {
            /** Entities Used */
            entities_used: string[];
            /** Chunks */
            chunks: components["schemas"]["ChunkRef"][];
        };
        /** ChatMetaEvent */
        ChatMetaEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "meta";
            data: components["schemas"]["ChatMetaData"];
        };
        /**
         * ChatResult
         * @description POST /api/chat. The final event plus the entities used (the §10 `final` data plus meta.entities_used).
         */
        ChatResult: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Citation Ok */
            citation_ok: boolean;
            /** Flags */
            flags?: string[];
            /** Memory Candidates */
            memory_candidates?: components["schemas"]["MemoryCandidate"][];
            /** Excluded Docs */
            excluded_docs?: string[];
            /** Entities Used */
            entities_used?: string[];
        };
        /** ChatTokenData */
        ChatTokenData: {
            /** Text */
            text: string;
        };
        /** ChatTokenEvent */
        ChatTokenEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            event: "token";
            data: components["schemas"]["ChatTokenData"];
        };
        /** ChatTurn */
        ChatTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /**
         * Chunk
         * @description GET /api/chunks/{chunk_id}. Owner only.
         */
        Chunk: {
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: string;
            /** Locator */
            locator: string;
            /** Text */
            text: string;
        };
        /** ChunkRef */
        ChunkRef: {
            /** N */
            n: number;
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: string;
            /** Locator */
            locator: string;
        };
        /** Citation */
        Citation: {
            /** N */
            n: number;
            /** Chunk Id */
            chunk_id: string;
            /** Doc Id */
            doc_id: string;
            /** Locator */
            locator: string;
            /** Quote */
            quote: string;
        };
        /** Claim */
        Claim: {
            /**
             * Claim
             * @enum {string}
             */
            claim: "income" | "loan_default_12m" | "age" | "percentage" | "result" | "board" | "unsupported";
            /** Op */
            op?: ("ge" | "is" | "eq") | null;
            /** Value */
            value?: boolean | number | string | null;
            /** Issuer Claim */
            issuer_claim?: ("income_ge_25000" | "income_ge_50000" | "income_ge_75000" | "income_ge_100000" | "loan_default_12m" | "age_over_18" | "age_over_21" | "percentage_ge_60" | "percentage_ge_75" | "percentage_ge_90" | "result_pass" | "board") | null;
        };
        /** ClaimInfo */
        ClaimInfo: {
            /**
             * Claim
             * @enum {string}
             */
            claim: "income" | "loan_default_12m" | "age" | "percentage" | "result" | "board" | "unsupported";
            /** Issuer Provable */
            issuer_provable: ("income_ge_25000" | "income_ge_50000" | "income_ge_75000" | "income_ge_100000" | "loan_default_12m" | "age_over_18" | "age_over_21" | "percentage_ge_60" | "percentage_ge_75" | "percentage_ge_90" | "result_pass" | "board")[];
            /** Favourable */
            favourable: ("YES" | "NO") | null;
        };
        /**
         * ClaimsOut
         * @description GET /api/claims and MCP list_disclosable_claims. Names only, never values.
         */
        ClaimsOut: {
            /** Claims */
            claims: components["schemas"]["ClaimInfo"][];
        };
        /** CreateReminderArgs */
        CreateReminderArgs: {
            /** Title */
            title: string;
            /** Date */
            date: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** CreateReminderCall */
        CreateReminderCall: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "create_reminder";
            args: components["schemas"]["CreateReminderArgs"];
            /** Preview */
            preview: string;
        };
        /** Document */
        Document: {
            /** Doc Id */
            doc_id: string;
            /** Path */
            path: string;
            /**
             * Source
             * @enum {string}
             */
            source: "pdf" | "note" | "chat";
            /** Doc Type */
            doc_type?: string | null;
            /**
             * Signature Status
             * @enum {string}
             */
            signature_status: "issuer_signed" | "unsigned" | "invalid";
            /** Iss */
            iss?: string | null;
            /** Text Hash */
            text_hash?: string | null;
            /** Ingested At */
            ingested_at: string;
            /** Removed At */
            removed_at?: string | null;
            /** Holder Status */
            holder_status?: ("verified" | "mismatch" | "unknown") | null;
        };
        /** DraftEmailArgs */
        DraftEmailArgs: {
            /** To */
            to: string;
            /** Subject */
            subject: string;
            /** Body */
            body: string;
            /** Attachments */
            attachments?: components["schemas"]["Attachment"][];
        };
        /** DraftEmailCall */
        DraftEmailCall: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "draft_email";
            args: components["schemas"]["DraftEmailArgs"];
            /** Preview */
            preview: string;
        };
        /** Entity */
        Entity: {
            /** Entity Id */
            entity_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "PERSON" | "PROJECT" | "CONCEPT" | "DECISION" | "ORG" | "PLACE" | "DOCUMENT" | "OBLIGATION" | "EVENT";
            /** Name */
            name: string;
            /** Attrs */
            attrs?: {
                [key: string]: string;
            };
        };
        /** Fact */
        Fact: {
            /** Fact Id */
            fact_id: string;
            /** Entity Id */
            entity_id: string;
            /** Field */
            field: string;
            /** Value */
            value: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "issuer_doc" | "extracted" | "owner_stated";
            /** Doc Id */
            doc_id?: string | null;
            /** Quote */
            quote?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "low";
        };
        /**
         * FactVersion
         * @description One entry in a field's timeline: a Fact plus when it was stored and whether it is current.
         */
        FactVersion: {
            /** Fact Id */
            fact_id: string;
            /** Entity Id */
            entity_id: string;
            /** Field */
            field: string;
            /** Value */
            value: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "issuer_doc" | "extracted" | "owner_stated";
            /** Doc Id */
            doc_id?: string | null;
            /** Quote */
            quote?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Superseded By */
            superseded_by?: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "low";
            /** Created At */
            created_at: string;
            /** Current */
            current: boolean;
        };
        /** FillRentalFormArgs */
        FillRentalFormArgs: {
            /** Fields */
            fields: {
                [key: string]: string;
            };
        };
        /** FillRentalFormCall */
        FillRentalFormCall: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "fill_rental_form";
            args: components["schemas"]["FillRentalFormArgs"];
            /** Preview */
            preview: string;
        };
        /** Graph */
        Graph: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /** Src */
            src: string;
            /** Dst */
            dst: string;
            /**
             * Rel
             * @enum {string}
             */
            rel: "WORKS_ON" | "PART_OF" | "ABOUT" | "RELATES_TO" | "DECIDED" | "LANDLORD_OF" | "EMPLOYED_BY" | "BANKS_WITH" | "STUDIED_AT" | "PAID" | "DUE_ON" | "PARTY_TO" | "MENTIONED_IN";
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            /** Source Chunk Id */
            source_chunk_id?: string | null;
            /** Doc Id */
            doc_id?: string | null;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "PERSON" | "PROJECT" | "CONCEPT" | "DECISION" | "ORG" | "PLACE" | "DOCUMENT" | "OBLIGATION" | "EVENT";
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description GET /api/health. `models` maps role (llm, fast, embed) -> configured name; `model_loaded` -> resident now.
         *     `local_inference`: OLLAMA_URL's host is loopback (models run on this machine).
         */
        Health: {
            /** Ollama */
            ollama: boolean;
            /** Models */
            models: {
                [key: string]: string;
            };
            /** Model Loaded */
            model_loaded: {
                [key: string]: boolean;
            };
            /** Db */
            db: boolean;
            /** Vault Dir */
            vault_dir: string;
            /** Local Inference */
            local_inference: boolean;
        };
        /**
         * Identity
         * @description GET /api/identity: the §6.6 identity anchor, masked. Never the full name, date of birth or ID number.
         */
        Identity: {
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "not_verified";
            /**
             * Source
             * @enum {string}
             */
            source: "aadhaar_okyc" | "signed_id" | "config";
            /** Issuer */
            issuer?: string | null;
            /** Name Initials */
            name_initials: string;
            /** Birth Year */
            birth_year?: number | null;
            /** Doc Id */
            doc_id?: string | null;
            /** Verified At */
            verified_at?: string | null;
        };
        /** IngestEvent */
        IngestEvent: {
            /** Seq */
            seq: number;
            /** Ts */
            ts: string;
            /** Path */
            path: string;
            /** Doc Id */
            doc_id: string;
            /**
             * Signature Status
             * @enum {string}
             */
            signature_status: "issuer_signed" | "unsigned" | "invalid";
            /** Holder Status */
            holder_status?: ("verified" | "mismatch" | "unknown") | null;
            /** Entities Added */
            entities_added: number;
            /** Facts Added */
            facts_added: number;
        };
        /** IngestEvents */
        IngestEvents: {
            /** Events */
            events: components["schemas"]["IngestEvent"][];
            /** Last Seq */
            last_seq: number;
        };
        /** IngestResult */
        IngestResult: {
            /** Path */
            path: string;
            /** Doc Id */
            doc_id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "pdf" | "note" | "chat";
            /**
             * Signature Status
             * @enum {string}
             */
            signature_status: "issuer_signed" | "unsigned" | "invalid";
            /** Holder Status */
            holder_status?: ("verified" | "mismatch" | "unknown") | null;
            /**
             * Chunks Added
             * @default 0
             */
            chunks_added: number;
            /**
             * Entities Added
             * @default 0
             */
            entities_added: number;
            /**
             * Facts Added
             * @default 0
             */
            facts_added: number;
        };
        /** IngestSyncOut */
        IngestSyncOut: {
            /** Ingested */
            ingested: components["schemas"]["IngestResult"][];
        };
        /** IngestUploadOut */
        IngestUploadOut: {
            /** Path */
            path: string;
        };
        /** MemoryCandidate */
        MemoryCandidate: {
            /** Candidate Id */
            candidate_id: string;
            /** Statement */
            statement: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "fact" | "decision";
            /** Field */
            field?: string | null;
            /** Value */
            value?: string | null;
            /** Valid From */
            valid_from?: string | null;
            /** Project Entity Id */
            project_entity_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "accepted" | "discarded";
            /** Created At */
            created_at: string;
        };
        /** OutboxItem */
        OutboxItem: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "eml" | "ics" | "pdf";
            /** Size */
            size: number;
            /** Created At */
            created_at: string;
        };
        /** Plan */
        Plan: {
            /** Instruction */
            instruction: string;
            /** Calls */
            calls: (components["schemas"]["DraftEmailCall"] | components["schemas"]["CreateReminderCall"] | components["schemas"]["FillRentalFormCall"] | components["schemas"]["SaveNoteCall"])[];
            /** Warnings */
            warnings?: string[];
        };
        /**
         * Proposal
         * @description decide.decide() output (§5.4). `actions` is empty for automatic outcomes.
         */
        Proposal: {
            /**
             * Answer Type
             * @enum {string}
             */
            answer_type: "ISSUER_PROOF" | "OWNER_ATTESTED" | "DECLINED" | "CANNOT_CONFIRM" | "REFUSED";
            claim: components["schemas"]["Claim"];
            /** Result */
            result?: boolean | string | null;
            /** Favourable */
            favourable?: boolean | null;
            /** Actions */
            actions?: ("approve" | "answer" | "decline" | "deny")[];
            /** Reason */
            reason: string;
        };
        /** QueueOut */
        QueueOut: {
            /** Requesters */
            requesters: components["schemas"]["Requester"][];
            /** Requests */
            requests: components["schemas"]["RequestView"][];
            /** Tasks */
            tasks: components["schemas"]["Task"][];
            wallet: components["schemas"]["WalletStatus"];
        };
        /** RequestDecisionIn */
        RequestDecisionIn: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "answer" | "decline" | "deny";
        };
        /**
         * RequestView
         * @description Owner-side view of one request.
         */
        RequestView: {
            /** Request Id */
            request_id: string;
            /** Requester Fp */
            requester_fp: string;
            /** Requester Name */
            requester_name?: string | null;
            /**
             * Channel
             * @enum {string}
             */
            channel: "web" | "mcp";
            /** Question */
            question: string;
            claim?: components["schemas"]["Claim"] | null;
            proposal?: components["schemas"]["Proposal"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending_pairing" | "pending" | "done";
            /** Answer Type */
            answer_type?: ("ISSUER_PROOF" | "OWNER_ATTESTED" | "DECLINED" | "CANNOT_CONFIRM" | "REFUSED") | null;
            /** Created At */
            created_at: string;
            /** Decided At */
            decided_at?: string | null;
        };
        /** Requester */
        Requester: {
            /** Fingerprint */
            fingerprint: string;
            /** Pubkey */
            pubkey: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "paired" | "blocked";
            /** Paired At */
            paired_at?: string | null;
        };
        /** RequesterDecisionIn */
        RequesterDecisionIn: {
            /** Approve */
            approve: boolean;
        };
        /** SaveNoteArgs */
        SaveNoteArgs: {
            /** Title */
            title: string;
            /** Markdown */
            markdown: string;
        };
        /** SaveNoteCall */
        SaveNoteCall: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            tool: "save_note";
            args: components["schemas"]["SaveNoteArgs"];
            /** Preview */
            preview: string;
        };
        /** Task */
        Task: {
            /** Task Id */
            task_id: string;
            /** Instruction */
            instruction: string;
            plan: components["schemas"]["Plan"];
            /**
             * Status
             * @enum {string}
             */
            status: "planned" | "approved" | "rejected" | "done" | "failed";
            /** Result */
            result?: components["schemas"]["ToolResult"][] | null;
            /** Created At */
            created_at: string;
            /** Decided At */
            decided_at?: string | null;
        };
        /** TaskDecisionIn */
        TaskDecisionIn: {
            /** Approve */
            approve: boolean;
        };
        /** TaskIn */
        TaskIn: {
            /** Instruction */
            instruction: string;
        };
        /** TeachIn */
        TeachIn: {
            /** Statement */
            statement: string;
        };
        /** TeachResult */
        TeachResult: {
            fact: components["schemas"]["Fact"];
            /** Superseded */
            superseded?: components["schemas"]["Fact"][];
        };
        /** ToolResult */
        ToolResult: {
            /**
             * Tool
             * @enum {string}
             */
            tool: "draft_email" | "create_reminder" | "fill_rental_form" | "save_note";
            /** Ok */
            ok: boolean;
            /** Output Path */
            output_path?: string | null;
            /** Detail */
            detail?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WalletStatus */
        WalletStatus: {
            /** By Type */
            by_type: components["schemas"]["WalletTypeStatus"][];
            /** Low */
            low?: string[];
        };
        /** WalletTypeStatus */
        WalletTypeStatus: {
            /** Credential Type */
            credential_type: string;
            /** Iss */
            iss: string;
            /** Unused */
            unused: number;
            /** Total */
            total: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_upload_api_ingest_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_upload_api_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_sync_api_ingest_sync_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestSyncOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_events_api_ingest_events_get: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestEvents"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identity_anchor_api_identity_get: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identity_remove_api_identity_delete: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identity_aadhaar_api_identity_aadhaar_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_identity_aadhaar_api_identity_aadhaar_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entities_api_entities_get: {
        parameters: {
            query?: {
                type?: ("PERSON" | "PROJECT" | "CONCEPT" | "DECISION" | "ORG" | "PLACE" | "DOCUMENT" | "OBLIGATION" | "EVENT") | null;
            };
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facts_api_facts_get: {
        parameters: {
            query?: {
                field?: string | null;
                current?: boolean;
            };
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fact"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_api_graph_get: {
        parameters: {
            query?: {
                entity_id?: string | null;
                hops?: number;
            };
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Graph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chunk_api_chunks__chunk_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_sync_api_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatIn"];
            };
        };
        responses: {
            /** @description text/event-stream of CONTRACT §10 events; each `data:` line is the `data` of one of these */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatMetaEvent"] | components["schemas"]["ChatTokenEvent"] | components["schemas"]["ChatFinalEvent"] | components["schemas"]["ChatDoneEvent"] | components["schemas"]["ChatErrorEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    teach_api_memory_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeachIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeachResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidate_decision_api_memory_candidates__candidate_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    memory_timeline_api_memory_timeline_get: {
        parameters: {
            query?: {
                field?: string | null;
            };
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tasks_api_tasks_get: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_decision_api_tasks__task_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_api_queue_get: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requester_decision_api_requesters__fp__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path: {
                fp: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequesterDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Requester"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_decision_api_requests__request_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestDecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wallet_status_api_wallet_get: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_log_api_audit_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    outbox_api_outbox_get: {
        parameters: {
            query?: never;
            header?: {
                "x-owner-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_ask_post: {
        parameters: {
            query?: never;
            header?: {
                "x-channel"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_result_api_ask__request_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-requester-fp": string;
                "x-ts": number;
                "x-sig": string;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claims_api_claims_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimsOut"];
                };
            };
        };
    };
}
